### ISSUE TITLE
Visual/audio indicator during mind control to show how long it has left before it ends

### ISSUE THREAD

**Issue by NikolasTzimoulis** [NikolasTzimoulis/Couriers#25]

**Comment by DimasDSF** [comment]
This could be implemented by making mind_control a lua modifier and then using the ability to attach it to the cast target.
It would also help with #21 as the courier could be made to appear as soon as the controlled hero dies instead of waiting for the timer to expire

[This](https://pastebin.com/Nu0TzzUj) should work for the modifier
Link it with
`LinkLuaModifier("modifier_courier_mind_control", "PATH TO THE MODIFIER FILE", LUA_MODIFIER_MOTION_NONE)` in the spell file or addon_game_mode:init
Then attach it in the ability `OnSpellStart` with `target:AddNewModifier(caster, nil, "modifier_courier_mind_control", {duration = duration})`

**Comment by NikolasTzimoulis** [comment]
@DimasDSF Just pushed an update that includes this, among other things. You really didn't have to go through the trouble of writing all that code!
